# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969815b76de29d0be2fc656ee6ed3206ef4a88d08c94c7b243b83c5178982415a15828b88a811fd2751d6b45876f13f806ce596581a648376bdffe73c6f3b3ca

test:
  secret_key_base: caa5ad70dfcea6b1d9ff8bd6699f9a8220fe45ed821b86cfb97122f92edd063c293cb30981cbd0a25f48e3983c62a2d9d3ddcd6973481af34511ecf4b8c8a807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
